import React, { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        {/* <div className="navbar-logo">Logo</div> */}
        <Link href="/">
          <a className="nav-link">Home</a>
        </Link>
        <ul className="navbar-links">
          {/* <li>
            <Link href="/about">
              <a className="nav-link">about</a>
            </Link>
          </li> */}
          <li>
            <Link href="/experience">
              <a className="nav-link">experience</a>
            </Link>
          </li>
          <li>
            <Link href="/contact">
              <a className="nav-link">contact</a>
            </Link>
          </li>
        </ul>
      </nav>

      <div className={styles.container}>{children}</div>

      <div className={styles.footerContainer}>
        <a
          href="https://www.linkedin.com/in/adrian-jendo/"
          className={styles.footerImg}
        >
          <Image alt="Linkedin" width={30} height={30} src="/linkedin.svg" />
        </a>
        <a href="https://github.com/adrianjendo" className={styles.footerImg}>
          <Image alt="Github" width={30} height={30} src="/github.svg" />
        </a>
        <a
          href="https://www.instagram.com/adrian.jendo/"
          className={styles.footerImg}
        >
          <Image alt="Instagram" width={30} height={30} src="/instagram.svg" />
        </a>
      </div>
    </div>
  );
};

export default Layout;
