import React, { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div className="navbar-logo">Logo</div>
        <ul className="navbar-links">
          <li>
            <Link href="/about">
              <a className="nav-link">about</a>
            </Link>
          </li>
          <li>
            <Link href="/experience">
              <a className="nav-link">experience</a>
            </Link>
          </li>
          <li>
            <Link href="/contact">
              <a className="nav-link">contact</a>
            </Link>
          </li>
        </ul>
      </nav>

      <div className={styles.container}>{children}</div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
